name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master

        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          exit-code: 1

  deploy:
    needs: scan
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            if [ ! -d ~/github-cicd-demo ]; then
              git clone https://github.com/didiemerhor1/github-cicd-demo.git ~/github-cicd-demo
            fi

            cd ~/github-cicd-demo

            git pull origin main

            docker stop flask-app || true
            docker rm flask-app || true

            docker build -t flask-app .

            docker run -d \
              --name flask-app \
              -p 5000:5000 \
              flask-app
